on: [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        
      - name: install LLVM
        run: sudo apt-get install -y llvm-toolchain-focal

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        continue-on-error: true  # WARNING: only for this example, remove it!
        with:
          command: build
          args: --release

